[build]
  base = "apps/client"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/characters/*"
  to = "https://shpoint-prod.onrender.com/characters/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/characters_assets/*"
  to = "https://shpoint-prod.onrender.com/characters/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
