[build]
  base = "apps/client"
  publish = "dist"
  command = "npm --workspace shpoint-client run build"

[build.environment]
  NODE_VERSION = "20"

# Disable Netlify's rate limiting for API calls
[[headers]]
  for = "/backend-api/*"
  [headers.values]
    X-RateLimit-Limit = "10000"
    X-RateLimit-Window = "900"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[redirects]]
  from = "/characters/*"
  to = "https://shpoint-prod.onrender.com/characters/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/characters_assets/*"
  to = "https://shpoint-prod.onrender.com/characters/:splat"
  status = 200
  force = true

# Special redirect for health endpoint
[[redirects]]
  from = "/backend-api/health"
  to = "https://shpoint-prod.onrender.com/health"
  status = 200
  force = true

[[redirects]]
  from = "/backend-api/*"
  to = "https://shpoint-prod.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/backend-auth/*"
  to = "https://shpoint-prod.onrender.com/auth/:splat"
  status = 200
  force = true

# User profile API proxy
[[redirects]]
  from = "/api/user/*"
  to = "https://shpoint-prod.onrender.com/api/user/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Google Search Console verification file - must be served directly
[[redirects]]
  from = "/google29ee34408b7b694e.html"
  to = "/google29ee34408b7b694e.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
