import { jsx as _jsx } from "react/jsx-runtime";
import React from "react";
import ReactDOM from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import "./index.css";
import "./styles/global.css";
import "./styles/shatterpoint-icons.css";
import "./lib/icons.css";
import AppRoutes from "./AppRoutes";
import { AuthProvider } from "./auth/AuthContext";
import { initTheme } from "./theme/theme-init";
initTheme();
ReactDOM.createRoot(document.getElementById("root")).render(_jsx(React.StrictMode, { children: _jsx(BrowserRouter, { children: _jsx(AuthProvider, { children: _jsx(AppRoutes, {}) }) }) }));
